# Generated by Django 2.2.5 on 2020-12-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jezyk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_jezyka', models.CharField(max_length=2, unique=True)),
                ('nazwa', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PoziomJezyka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod_poziomu', models.CharField(choices=[('A1', 'Poziom A1'), ('A2', 'Poziom A2'), ('B1', 'Poziom B1'), ('B2', 'Poziom B2'), ('C1', 'Poziom C1'), ('C2', 'Poziom C2')], max_length=2)),
                ('opis', models.CharField(max_length=800)),
            ],
        ),
    ]
