# Generated by Django 2.2.5 on 2020-12-04 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pracownik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('data_urodzenia', models.DateField()),
                ('pesel', models.CharField(max_length=13, null=True, unique=True)),
                ('email', models.CharField(max_length=30, unique=True)),
                ('nr_telefonu', models.CharField(max_length=13, unique=True)),
                ('nr_konta_bankowego', models.CharField(max_length=26, unique=True)),
                ('data_zatrudnienia', models.DateField()),
                ('data_zwolnienia', models.DateField(null=True)),
                ('id_adresu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parki.Adres')),
                ('id_parku_rozrywki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parki.ParkRozrywki')),
            ],
        ),
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30, unique=True)),
                ('opis', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Wynagrodzenie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_wynagrodzenia', models.DateField()),
                ('kwota_podstawowa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kwota_dodatkowa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_pracownika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pracownicy.Pracownik')),
            ],
        ),
        migrations.CreateModel(
            name='Wlasciciel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('id_adresu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parki.Adres')),
                ('id_parku_rozrywki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parki.ParkRozrywki')),
            ],
        ),
        migrations.AddField(
            model_name='pracownik',
            name='id_stanowiska',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pracownicy.Stanowisko'),
        ),
    ]
