# Generated by Django 2.2.5 on 2020-12-04 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atrakcja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('producent', models.CharField(max_length=30)),
                ('typ_atrakcji', models.CharField(max_length=30)),
                ('opis', models.CharField(max_length=400)),
                ('wymagania_wiekowe', models.IntegerField()),
                ('status', models.CharField(choices=[('Otwarty', 'Otwarty'), ('Zamkniety', 'Zamknięty')], max_length=30)),
                ('wysokosc', models.IntegerField(null=True)),
                ('predkosc', models.IntegerField(null=True)),
                ('przeciazenie', models.IntegerField(null=True)),
                ('przepustowosc', models.IntegerField(null=True)),
                ('dlugosc_trasy', models.IntegerField(null=True)),
                ('data_przegladu', models.DateField(null=True)),
                ('waznosc_przegladu', models.DateField(null=True)),
                ('id_sektora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parki.Sektor')),
            ],
        ),
    ]
