# Generated by Django 2.2.5 on 2020-12-04 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bilet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('czy_rabat', models.BooleanField(default=False)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_punktu_sprzedazy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parki.PunktSprzedazy')),
            ],
        ),
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('nr_telefonu', models.CharField(max_length=13)),
                ('id_parku_rozrywki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parki.ParkRozrywki')),
            ],
        ),
        migrations.CreateModel(
            name='Rabat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('wartosc', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Zamowienie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_zakupy', models.DateTimeField(auto_now_add=True)),
                ('data_aktywacji', models.DateTimeField()),
                ('data_waznosci', models.DateTimeField()),
                ('id_biletu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zamawianie.Bilet')),
                ('id_klienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zamawianie.Klient')),
            ],
        ),
        migrations.AddField(
            model_name='bilet',
            name='id_rabatu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zamawianie.Rabat'),
        ),
    ]
