# Generated by Django 2.2.5 on 2020-12-04 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miasto', models.CharField(max_length=30)),
                ('ulica', models.CharField(max_length=30)),
                ('nr_lokalu', models.CharField(max_length=30)),
                ('kod_pocztowy', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ParkRozrywki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('data_zalozenia', models.DateField()),
                ('id_adresu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parki.Adres')),
            ],
        ),
        migrations.CreateModel(
            name='Sektor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Otwarty', 'Otwarty'), ('Zamkniety', 'Zamknięty')], max_length=30)),
                ('opis', models.CharField(max_length=400)),
                ('data_zalozenia', models.DateField()),
                ('id_parku_rozrywki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parki.ParkRozrywki')),
            ],
        ),
        migrations.CreateModel(
            name='PunktSprzedazy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('liczba_kas', models.IntegerField()),
                ('status', models.CharField(choices=[('Otwarty', 'Otwarty'), ('Zamkniety', 'Zamknięty')], max_length=30)),
                ('id_parku_rozrywki', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parki.ParkRozrywki')),
            ],
        ),
    ]
